name: Poetry version update control

on:
  workflow_dispatch:
    inputs:
      api_token:
        description: 'API token'
        required: true
jobs:
    versioning:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.1
          with:
            github_token: ${{ secrets.TEAM_HENRIQUE_TOKEN }}
       